export const AUTH_STRINGS = {
  AUTH: {
    TITLE: 'Masuk ke sistem AgriSync',
    EMAIL_LABEL: 'Alamat Email',
    LOGIN_BUTTON: 'Masuk',
    REQUEST_PROMPT: 'Minta Akses Pegawai Baru',
    REQUEST_SENT_TITLE: 'Permohonan Terkirim',
    REQUEST_SENT_DESC: 'Permohonan akses Anda telah dikirim ke Supervisor. Anda akan dihubungi melalui WhatsApp jika disetujui.',
    FULL_NAME_LABEL: 'Nama Lengkap',
    PHONE_LABEL: 'Nomor Telepon',
    REQUEST_SUBMIT: 'Kirim Permohonan',
    REQUEST_BACK: 'Kembali',
    MAGIC_LINK_SENT: 'Tautan Ajaib Terkirim',
    MAGIC_LINK_CHECK: 'Silakan periksa kotak masuk email Anda.',
    INVALID_CREDENTIALS: 'Format email atau kata sandi tidak valid.',
    COMPANY_CODE_LABEL: 'Kode Workspace (Supervisor)',
  },
  ONBOARDING: {
    TITLE: 'Workspace Baru',
    SUBTITLE: 'Tampaknya Anda belum terdaftar di perusahaan mana pun. Daftarkan perusahaan Anda untuk memulai.',
    COMPANY_LABEL: 'Nama Perusahaan / Lahan',
    COMPANY_PLACEHOLDER: 'Misal: PT. Kebun Raya',
    FULL_NAME_LABEL: 'Nama Lengkap (Sesuai KTP)',
    FULL_NAME_PLACEHOLDER: 'Misal: Budi Santoso',
    PHONE_LABEL: 'Nomor WhatsApp Aktif',
    PHONE_PLACEHOLDER: 'Misal: 08123456789',
    SUBMIT_BUTTON: 'Buat Workspace',
    SUCCESS: 'Workspace perusahaan berhasil dibuat!',
    ERROR_CREATE_COMPANY: 'Gagal membuat perusahaan.',
    ERROR_CREATE_PROFILE: 'Gagal mendaftarkan profil supervisor.',
    SPLIT_WORKER_TITLE: 'Saya Pekerja Lapangan',
    SPLIT_WORKER_DESC: 'Bergabung ke workspace yang sudah ada.',
    SPLIT_ADMIN_TITLE: 'Saya Supervisor / Admin',
    SPLIT_ADMIN_DESC: 'Buat workspace baru untuk perusahaan Anda.',
    WAITING_INVITE_TITLE: 'Menunggu Undangan',
    WAITING_INVITE_DESC: 'Untuk bergabung, mintalah Supervisor Anda untuk mengundang email berikut dari Dasbor mereka:',
    REFRESH_BUTTON: 'Cek Status',
    ADMIN_CONFIRM: 'Penting: Saya adalah manajemen/pemilik, BUKAN pekerja lapangan. Pekerja lapangan tidak boleh membuat workspace.',
    WELCOME_TITLE: 'Selamat Datang',
    WELCOME_DESC: 'Pilih jalur untuk memulai AgriSync.',
    BACK_BUTTON: 'Kembali',
    LOGOUT: 'Keluar',
    WORKER_REQ_TITLE: 'Minta Akses Workspace',
    WORKER_REQ_DESC: 'Masukkan Kode Workspace yang diberikan oleh Supervisor Anda.',
    WORKSPACE_CODE_LABEL: 'Kode Workspace',
    WORKSPACE_CODE_PLACEHOLDER: 'Misal: AB12CD',
    WORKER_REQ_BTN: 'Minta Akses',
    REQUEST_SUCCESS: 'Permintaan akses berhasil dikirim!',
  },
  VALIDATION: {
    PHOTO_REQUIRED: 'Foto bukti wajib disertakan.',
    LOCATION_REQUIRED: 'Sedang memvalidasi titik koordinat GPS Anda...',
    PHONE_REQUIRED: 'Nomor WhatsApp wajib diisi.',
    PHONE_FORMAT: 'Nomor WhatsApp tidak valid (10-13 digit angka, diawali 08 atau 628).',
    BIO_MAX_LENGTH: 'Bio maksimal 100 karakter.',
    FULL_NAME_REQUIRED: 'Nama lengkap wajib diisi.',
    FULL_NAME_FORMAT: 'Nama lengkap hanya boleh berisi huruf (minimal 3 karakter, tanpa angka).',
    FULL_NAME_MAX: 'Nama lengkap maksimal 100 karakter.',
    EMAIL_FORMAT: 'Format email tidak valid.',
    EMAIL_PROVIDER_INVALID: 'Gunakan email yang valid (contoh: gmail.com atau domain perusahaan).',
    EMAIL_TYPO: 'Maksud Anda {0}? Periksa kembali ejaan email Anda.',
    COMPANY_REQUIRED: 'Nama perusahaan wajib diisi.',
    COMPANY_FORMAT: 'Nama perusahaan minimal 2 karakter alfanumerik.',
    COMPANY_MAX: 'Nama perusahaan maksimal 100 karakter.',
    CONFIRM_REQUIRED: 'Anda wajib mencentang persetujuan ini.',
    COMPANY_CODE_REQUIRED: 'Kode Workspace wajib diisi.',
    COMPANY_CODE_FORMAT: 'Kode Workspace harus 4-10 karakter alfanumerik.',
  },
  PLACEHOLDERS: {
    EMAIL: 'anda@perusahaan.com',
    PHONE: '08123456789',
    FULL_NAME: 'Budi Santoso',
    COMPANY: 'PT. Agri Maju',
    BIO: 'Tulis sedikit tentang Anda...',
    COMPANY_CODE: 'Masukkan kode dari supervisor...',
  },
} as const;
