export const BILLING_STRINGS = {
  BILLING: {
    TITLE: 'Pilih Paket Sesuai Skala Operasional Anda',
    SUBTITLE: 'Mulai uji coba tanpa batas waktu, dan tingkatkan kapasitas seiring bertumbuhnya bisnis perkebunan Anda.',
    FREE_TIER: 'Gratis',
    FREE_DESC: 'Bebas biaya selamanya, tanpa kartu kredit.',
    PRICE_FREE: 'Rp 0',
    FREE_BTN: 'Paket Saat Ini',
    CURRENT_PLAN_BADGE: 'PAKET SAAT INI',
    BASE_PLAN_BADGE: 'PAKET DASAR',
    ACTIVE_BADGE: 'AKTIF',
    FREE_FEATURES: [
      'Maks. 5 Pekerja Lapangan',
      'Pelaporan Insiden Dasar',
      'Sinkronisasi Data Offline',
      'Peta Sebaran Laporan',
    ],
    PRO_TIER: 'Profesional',
    PRO_DESC: 'Dirancang untuk optimalisasi operasional menengah.',
    PRICE_PRO: 'Rp 299rb',
    PRICE_PRO_SUFFIX: '/bln',
    UPGRADE_BTN: 'Upgrade ke Profesional',
    PROCESSING: 'Memproses...',
    RECOMMENDED: 'Paling Diminati',
    PRO_FEATURES: [
      'Hingga 50 Pekerja Lapangan',
      'Pemantauan Peta Real-time',
      'Notifikasi Email Otomatis',
      'Dukungan Teknis Prioritas',
    ],
    ENT_TIER: 'Enterprise',
    ENT_DESC: 'Solusi kustom untuk korporasi skala besar.',
    PRICE_ENT: 'Hubungi Sales',
    ENT_BTN: 'Jadwalkan Demo',
    ENT_BADGE: 'Segera Hadir',
    ENT_FEATURES: [
      'Pekerja Lapangan Tanpa Batas',
      'Integrasi API Perusahaan',
      'Manajemen Akses Khusus',
      'Dedicated Account Manager',
    ],
    PAYMENT_SUCCESS: 'Pembayaran berhasil! Mengaktifkan paket PRO...',
    PAYMENT_PENDING: 'Menunggu pembayaran diselesaikan...',
    PAYMENT_ERROR: 'Pembayaran gagal atau kadaluarsa.',
    PAYMENT_CANCELLED: 'Pembayaran dibatalkan.',
    DAYS_LEFT: (days: number) => `${days} hari tersisa`,
    UPGRADE_SHORT: 'Upgrade',
    UPGRADE_LONG: 'Upgrade Workspace',
    SUBSCRIPTION_BADGE: 'Paket Berlangganan',
    START_FREE: 'Mulai Gratis',
    SELECT_PRO: 'Pilih Paket Pro',
    LEARN_ENT: 'Pelajari Enterprise',
  },
} as const;
