export const COMMON_STRINGS = {
  APP_NAME: 'AgriSync',
  UI: {
    CAMERA_CAPTURE: 'Ambil Foto',
    RETAKE_PHOTO: 'Ulangi',
    SUBMIT_REPORT: 'Kirim Laporan',
    SYNC_PENDING: 'Menyinkronkan data...',
    SYNC_SUCCESS: 'Semua data tersinkronisasi.',
    ONLINE_MODE: 'Online',
    OFFLINE_MODE: 'Offline',
    LOADING: 'Memproses...',
    REPORT_SENT: 'Laporan berhasil dikirim.',
    REPORT_SAVED_LOCAL: 'Laporan disimpan di perangkat (Offline).',
    REPORT_SAVED_SYNCING: 'Laporan disimpan di perangkat. Menyinkronkan...',
    ALREADY_SYNCED: 'Tidak ada data tertunda.',
    QUEUE_TITLE: 'Antrean Sinkronisasi',
    QUEUE_EMPTY: 'Semua laporan telah tersinkronisasi dengan server.',
    ITEMS_WAITING: 'Menunggu',
    TOGGLE_THEME: 'Ubah Tema',
    PREVIEW_ALT: 'Pratinjau',
    AVATAR_ALT: 'Avatar',
    LAT_LABEL: 'Lat',
    LNG_LABEL: 'Lng',
    UPDATE_AVAILABLE: 'Versi baru tersedia!',
    UPDATE_NOW: 'Perbarui Sekarang',
    COPY_CODE: 'Copy Code',
    PROFILE_ALT: 'Profile',
    BACK_TO_DASHBOARD: 'Kembali ke Dasbor',
    PAGINATION_SHOWING: (start: number, end: number, total: number, entity: string) =>
      `Menampilkan ${start} - ${end} dari ${total} ${entity}`,
    PAGINATION_PAGE: (current: number, total: number) => `Hal ${current} dari ${total}`,
    PAGINATION_PREV: 'Prev',
    PAGINATION_NEXT: 'Next',
    CANCEL: 'Batal',
    CONFIRM: 'Konfirmasi',
    PROCESSING: 'Memproses...',
    COPIED: 'Tersalin',
    FLIP_CAMERA: 'Balikkan Kamera',
    DATE_COLUMN: 'Tanggal',
    NO_MATCHING_REPORTS: 'Tidak ada laporan yang sesuai kriteria.',
    PAGE_NOT_FOUND: 'Halaman Tidak Ditemukan',
    NOT_FOUND_DESC: 'Halaman yang Anda cari tidak ditemukan atau telah dipindahkan.',
  },
  THEME: {
    TOGGLE: 'Ganti Tema',
    DARK: 'Gelap',
    LIGHT: 'Terang',
    SYSTEM: 'Sistem',
  },
  TITLES: {
    LANDING: 'AgriSync — Platform Manajemen Perkebunan',
    DOCS: 'Dokumentasi — AgriSync Platform',
    LOGIN: 'Login',
    SUBSCRIPTION: 'Subscription',
    NOT_FOUND: '404 Not Found',
    PROFILE: 'Profile',
    REPORTS: 'Reports',
    DASHBOARD: 'Dashboard',
    WORKER_AREA: 'Worker Area',
    INBOX: 'Inbox',
    ONBOARDING: 'Onboarding',
    NOTIFICATIONS: 'Notifications',
  },
  DOCS: {
    DOCS_TITLE: 'Docs',
    BACK_TO_HOME: 'Kembali ke Beranda',
    LOGIN_PORTAL: 'Portal Login',
    SEARCH_PLACEHOLDER: 'Cari dokumentasi atau panduan...',
    NOTE: 'Catatan:',
    TOPIC_NOT_FOUND: 'Topik Tidak Ditemukan',
    TOPIC_NOT_FOUND_DESC: 'Coba gunakan kata kunci pencarian yang lain.',
  },
  ERRORS: {
    GPS_UNAVAILABLE: 'Izin lokasi (GPS) diperlukan untuk mengirim laporan.',
    GPS_TIMEOUT: 'Pencarian lokasi terlalu lama. Pastikan sinyal GPS stabil.',
    GPS_GENERIC: 'Gagal mendeteksi lokasi.',
    GPS_DENIED: 'Akses GPS Ditolak',
    CAMERA_DENIED: 'Izin kamera ditolak. Akses kamera diwajibkan untuk mengambil foto bukti.',
    CAMERA_PROCESS_FAILED: 'Gagal memproses gambar.',
    STORAGE_FULL: 'Penyimpanan perangkat penuh.',
    SYNC_FAILED: 'Gagal mengirim ke server. Laporan Anda disimpan secara offline di perangkat dan akan dikirim saat sinyal stabil.',
    GENERIC: 'Terjadi kendala sistem. Silakan coba beberapa saat lagi.',
    SYNC_VALIDATION_GPS: 'Laporan ditolak: Lokasi GPS tidak akurat.',
    SYNC_VALIDATION_IMAGE: 'Laporan ditolak: Foto bukti tidak valid.',
    FETCH_STATS_FAILED: 'Gagal memuat statistik.',
    FETCH_DATA_FAILED: 'Gagal memuat data.',
    CHECKOUT_FAILED: 'Gagal membuat sesi pembayaran.',
    CHECKOUT_PROCESS_FAILED: (msg: string) => `Gagal memproses pembayaran: ${msg}`,
    CLAIM_RECORD_FAILED: (msg: string) => `Gagal mengklaim data pegawai: ${msg}`,
    COPY_FAILED: 'Gagal menyalin teks.',
    CONNECTION_TIMEOUT: 'Koneksi terputus. Pastikan internet Anda stabil atau matikan AdBlocker.',
    AUTH_REQUIRED_PROFILE: 'Autentikasi diperlukan untuk mengubah profil',
  },
} as const;
