export const DASHBOARD_STRINGS = {
  DASHBOARD: {
    TITLE: 'Pusat Kendali',
    ROLE_ADMIN: 'Supervisor',
    STATS_TOTAL_REPORTS: 'Total Laporan',
    STATS_ACTIVE_WORKERS: 'Pekerja Aktif',
    STATS_PENDING_SYNC: 'Sinkronisasi Tertunda',
    INVITE_TITLE: 'Undang Pegawai',
    INVITE_DESC: 'Masukkan email pegawai untuk memberikan akses ke sistem.',
    FORM_VALIDATION_ERROR: 'Validasi Gagal: Silakan periksa pesan error merah di bawah kolom input.',
    ROLE_LABEL: 'Peran',
    INVITE_WORKER_COUNT_LABEL: 'Kuota Pekerja',
    INVITE_PLACEHOLDER: 'email.pegawai@perusahaan.com',
    INVITE_BUTTON: 'Kirim Undangan',
    INVITE_SUCCESS: 'Undangan berhasil dikirim. Pegawai sudah bisa login menggunakan email tersebut.',
    INVITE_UPGRADE_REQUIRED: (max: number) =>
      `Anda telah mencapai batas maksimal ${max} pegawai untuk Paket Gratis. Pertimbangkan untuk upgrade ke Pro.`,
    INVITE_WORKER_COUNT_LABEL_OLD: 'Pekerja Lapangan',
    COPY_CODE_SUCCESS: 'Kode Perusahaan disalin! Kirimkan ke Pekerja Anda.',
    ROLE_SUPERVISOR_OPT: 'Supervisor',
    REQ_TITLE: 'Permintaan Bergabung',
    REQ_EMPTY: 'Tidak ada permintaan bergabung saat ini.',
    REQ_ACCEPT: 'Terima',
    REQ_REJECT: 'Tolak',
    REQ_WA_PREFIX: 'WA:',
    EMP_TABLE_TITLE: 'Daftar Pegawai',
    EMP_TABLE_COL_PROFILE: 'Profil',
    EMP_TABLE_COL_INFO: 'Info Pegawai',
    EMP_TABLE_COL_JOINED: 'Bergabung Sejak',
    EMP_TABLE_COL_ROLE: 'Peran',
    EMP_TABLE_COL_ACTION: 'Aksi',
    EMP_LOADING: 'Memuat data pegawai...',
    EMP_EMPTY: 'Belum ada pegawai terdaftar.',
    EMP_ACTION_MAKE_SPV: 'Jadikan Supervisor',
    EMP_ACTION_MAKE_WORKER: 'Jadikan Pekerja',
    EMP_ACTION_REVOKE: 'Cabut Akses',
    STATUS_PENDING: 'PENDING',
    EMP_YOU: 'Anda',
    COPY_CODE_TOOLTIP: 'Salin Kode Perusahaan',
    MEMBERS: 'Anggota',
    SEARCH_EMP_PLACEHOLDER: 'Cari nama atau email...',
    MEMBERS_LOWER: 'anggota',
    VIEW_MAP_LABEL: 'Peta',
    VIEW_LIST_LABEL: 'Daftar',
  },
  ACTION_MESSAGES: {
    ROLE_UPDATE_SUCCESS: 'Peran pegawai berhasil diubah.',
    ROLE_UPDATE_FAILED: 'Gagal mengubah peran.',
    ACCESS_REVOKE_CONFIRM: 'Yakin ingin mencabut akses pegawai ini?',
    ACCESS_REVOKE_SUCCESS: 'Akses pegawai telah dicabut.',
    ACCESS_REVOKE_FAILED: 'Gagal mencabut akses.',
    CONFIRM_REVOKE: 'Ya, Cabut Akses',
    ACCESS_REVOKE_WARNING: 'Tindakan ini tidak dapat dibatalkan dan akan langsung memutus akses mereka ke sistem.',
    ACCESS_REVOKE_CONFIRM_DESC: 'Apakah Anda yakin ingin mencabut akses untuk ',
    PROFILE_UPDATE_SUCCESS: 'Profil berhasil disimpan.',
    IMAGE_PROCESS_FAILED: 'Gagal memproses gambar.',
    INVITE_FAILED_DUPLICATE: 'Email tersebut sudah terdaftar.',
    REQ_FAILED: 'Gagal mengirim permintaan.',
    REQ_ACCEPT_FAILED: 'Gagal menerima akses.',
    REQ_ACCEPT_SUCCESS: 'Permintaan diterima.',
    REQ_REJECT_SUCCESS: 'Permintaan ditolak.',
  },
  SHARE: {
    SUCCESS_TITLE: 'Akses Berhasil Ditambahkan!',
    SUCCESS_DESC: 'Pekerja telah masuk ke whitelist. Bagikan tautan akses agar mereka bisa segera login.',
    WHATSAPP: 'WhatsApp',
    EMAIL: 'Email',
    CLOSE: 'Tutup',
    COPY_CODE: 'Salin Kode Workspace',
    GREETING: (name: string, role: string, email: string, url: string) =>
      `Halo ${name},\n\nAkses Anda sebagai ${role} telah ditambahkan ke sistem AgriSync.\n\nSilakan login menggunakan email Anda (${email}) di:\n${url}\n\nTerima kasih!`,
    ROLE_SUPERVISOR: 'Supervisor',
    ROLE_WORKER: 'Worker',
  },
} as const;
