export const WORKER_STRINGS = {
  WORKER: {
    TITLE: 'AgriSync',
    SUBTITLE: 'Modul Kamera',
    ROLE_WORKER: 'Worker',
    ZONE_PLACEHOLDER: 'Pilih Blok Lahan',
    CATEGORY_PLACEHOLDER: 'Pilih Kategori',
    NOTES_PLACEHOLDER: 'Tambahkan catatan (Opsional)...',
    HISTORY_TITLE: 'Riwayat Laporan Saya',
    HISTORY_COUNT: (count: number) => `${count} Laporan ditemukan`,
    HISTORY_EMPTY: 'Belum ada laporan.',
    HISTORY_EMPTY_SUB: 'Laporan yang Anda kirim akan muncul di sini.',
    HISTORY_BACK: 'Kembali ke daftar',
    HISTORY_YOUR_REPORT: 'Laporan Anda',
    HISTORY_NO_REPLY: 'Belum ada tanggapan dari Supervisor.',
    REPORT_HISTORY: 'Riwayat Laporan',
    TOTAL_YOUR_REPORTS: 'Total Laporan Anda',
    PRO_PLAN_LABEL: 'Professional Plan',
    FREE_PLAN_LABEL: 'FREE',
    INBOX_LABEL: 'INBOX',
    PACKAGE_PREFIX: 'PAKET',
  },
  SETTINGS: {
    TITLE: 'Pengaturan Profil',
    AVATAR_TITLE: 'Foto Profil',
    PHONE_TITLE: 'Nomor WhatsApp',
    BIO_TITLE: 'Bio Singkat',
    SAVE_BUTTON: 'Simpan Profil',
  },
  MAP: {
    WORKER_TITLE: 'Lokasi Anda Saat Ini',
    SPV_TITLE: 'Peta Pantauan Laporan',
    LOCATING: 'Mencari Satelit GPS...',
    FOUND: 'Lokasi Akurat',
    REPORT_BY: 'Pelapor',
    UNKNOWN_REPORTER: 'Anonim',
    STATUS_PENDING: 'Menunggu',
    STATUS_INVESTIGATING: 'Diproses',
    STATUS_RESOLVED: 'Selesai',
    UPDATE_BTN: 'Kirim',
    COMMENT_PLACEHOLDER: 'Tinggalkan komentar (opsional)...',
    DATA_COUNT: (count: number) => `${count} Data`,
    NEW_REPORT_RECEIVED: 'Laporan baru diterima!',
    REPORT_IMAGE_ALT: 'Foto Bukti Laporan',
    REPORT_DETAILS: 'Detail Laporan',
    UNKNOWN_ZONE: 'Zona Tidak Diketahui',
    REPORTER: 'Pelapor',
    SYSTEM: 'Sistem',
    ACTIVITY_LOG: 'Log Aktivitas & Komentar',
    NO_COMMENTS: 'Belum ada komentar.',
    STATUS: 'Status',
    VIEW_ON_MAP: 'Lihat di Peta Internal',
    DETAIL_AND_CHAT: 'Detail & Chat',
    JUST_NOW: 'Baru saja',
    REPORT_FIELD: 'Laporan Lapangan',
    SEARCH_REPORT_PLACEHOLDER: 'Cari pelapor, zona...',
    CLEAR_DATE_FILTER: 'Hapus filter tanggal',
    ALL: 'Semua',
    REPORTS_LOWER: 'laporan',
    WAITING_SIGNAL: 'Menunggu Sinyal',
    SYNCING: 'Menyinkronkan...',
    PENDING_REPORTS: 'laporan tertunda',
  },
} as const;
