export const LANDING_STRINGS = {
  NAV: {
    BRAND: 'AgriSync',
    TAGLINE: 'Enterprise Agro-Platform',
    NAV_FEATURES: 'Fitur Unggulan',
    NAV_ARCHITECTURE: 'Arsitektur',
    NAV_PRICING: 'Paket Harga',
    NAV_DOCS: 'Dokumentasi',
    PORTAL_BTN: 'Masuk Portal',
    OPEN_DASHBOARD: 'Buka Dasbor',
    OPEN_WORKSPACE: 'Buka Workspace',
  },
  HERO: {
    BADGE: 'v2.0.0 Enterprise • Offline-First AgriTech Platform',
    TITLE_LINE1: 'Platform Manajemen Perkebunan',
    TITLE_LINE2: 'Modern & Pelaporan Lapangan Real-time',
    SUBTITLE: 'Solusi SaaS multi-tenant dengan kapabilitas offline-first penuh, pelacakan GPS terintegrasi, dan notifikasi insiden instan untuk efisiensi kebun tanpa hambatan sinyal.',
    CTA_PRIMARY: 'Mulai Sekarang',
    CTA_DOCS: 'Buka Dokumentasi Teknis',
    CTA_ARCHITECTURE: 'Eksplor Arsitektur',
    SIM_TAG: 'Live Pipeline State',
    SIM_OFFLINE: 'Mode Lapangan (Tanpa Sinyal)',
    SIM_SYNCED: 'Auto-Sync Berhasil (100%)',
    SIM_GPS: '-2.5489° S, 111.5241° E • Blok B Sawit',
  },

  METRICS: [
    { label: 'Uptime SLA', value: '99.98%', desc: 'Ketersediaan layanan cloud' },
    { label: 'Sync Latency', value: '< 120ms', desc: 'Saat sinyal kembali online' },
    { label: 'Storage Safety', value: '100% RLS', desc: 'Isolasi data antar tenant' },
    { label: 'Field Mode', value: 'Zero Signal', desc: 'Bekerja penuh di remote area' },
  ],
  FEATURES: {
    SECTION_BADGE: 'Kapabilitas Sistem',
    TITLE: 'Dirancang Khusus untuk Tantangan Nyata di Lapangan',
    SUBTITLE: 'Teknologi tangguh yang menggabungkan kemudahan aplikasi seluler pekerja dengan kendali komprehensif supervisor.',
    ITEMS: [
      {
        id: 'offline-first',
        title: 'Offline-First Engine',
        desc: 'Pekerja dapat mengambil foto dan mencatat insiden di pelosok tanpa koneksi internet. Data tersimpan aman di IndexedDB dan tersinkronisasi otomatis.',
        tag: 'IndexedDB & Dexie',
      },
      {
        id: 'gps-mapping',
        title: 'Geotagging & Blok GIS',
        desc: 'Koordinat GPS akurat terekam otomatis pada setiap foto insiden, dipetakan secara interaktif per blok zona kebun.',
        tag: 'Leaflet GIS',
      },
      {
        id: 'multi-tenancy',
        title: 'Isolasi Tenant & Keamanan RLS',
        desc: 'Arsitektur multi-tenant dengan PostgreSQL Row-Level Security. Data setiap perkebunan terisolasi penuh dan terlindungi dari kebocoran.',
        tag: 'PostgreSQL 15 RLS',
      },
      {
        id: 'automated-pipeline',
        title: 'Notifikasi Insiden Instan',
        desc: 'Edge function asinkron mendispatch email tanda terima ke pekerja dan alert prioritas tinggi ke supervisor saat ada insiden kritis.',
        tag: 'Deno Edge & Resend',
      },
      {
        id: 'rbac-system',
        title: 'Manajemen Akses Cepat',
        desc: 'Undang pekerja via email atau tautan WhatsApp. Pekerja baru mengklaim akses secara instan dengan kode unik perusahaan.',
        tag: 'Claim Token RPC',
      },
      {
        id: 'billing-ready',
        title: 'Billing & Kuota Fleksibel',
        desc: 'Integrasi Midtrans SNAP untuk pembayaran lokal instan dengan verifikasi signature HMAC SHA-512 backend yang aman.',
        tag: 'Midtrans SNAP',
      },
    ],
  },
  ARCHITECTURE: {
    SECTION_BADGE: 'Alur Hulu ke Hilir',
    TITLE: 'Bagaimana Data Bergerak dari Lapangan ke Meja Supervisor',
    SUBTITLE: 'Pipeline data tangguh yang menjamin tidak ada laporan insiden yang hilang meski jaringan internet terputus.',
    STEPS: [
      {
        step: '01',
        title: 'Kamera & GPS Lapangan',
        desc: 'Pekerja mengambil foto bukti insiden dan sistem mengunci koordinat GPS di blok kebun.',
        icon: 'Camera',
      },
      {
        step: '02',
        title: 'Persistensi Lokal Dexie',
        desc: 'Data langsung ditulis ke IndexedDB lokal sehingga UI tetap responsif tanpa menunggu jaringan.',
        icon: 'Database',
      },
      {
        step: '03',
        title: 'Sync Engine & Supabase RLS',
        desc: 'Saat mendeteksi sinyal, worker mengunggah media ke Supabase Storage & database PostgreSQL.',
        icon: 'CloudUpload',
      },
      {
        step: '04',
        title: 'Edge Alert & Dashboard GIS',
        desc: 'pg_net memicu Edge Function untuk email insiden dan memperbarui peta dasbor supervisor secara live.',
        icon: 'BellRing',
      },
    ],
  },
  CTA: {
    TITLE: 'Tingkatkan Efisiensi & Visibilitas Perkebunan Anda Hari Ini',
    SUBTITLE: 'Mulai dengan akun gratis tanpa kartu kredit. Akses seluruh fitur pelaporan lapangan sekarang.',
    BUTTON: 'Masuk ke AgriSync',
    DOCS_LINK: 'Pelajari Dokumentasi Teknis',
  },
  FOOTER: {
    BRAND: 'AgriSync',
    TAGLINE: 'Platform Pelaporan Lapangan & Manajemen Perkebunan Multi-Tenant.',
    STATUS: 'Sistem Operasional Normal',
    COPYRIGHT: '© 2026 AgriSync Enterprise. Hak Cipta Dilindungi.',
    LEGAL: 'Privasi & Keamanan Data Berstandar PostgreSQL RLS',
    COL_PRODUCTS_TITLE: 'Produk & Fitur',
    PRODUCTS: [
      { label: 'Offline-First Engine', href: '#features' },
      { label: 'Geotagging & Blok GIS', href: '#features' },
      { label: 'Alur Hulu ke Hilir', href: '#architecture' },
      { label: 'Paket Harga & Kuota', href: '#pricing' },
    ],
    COL_DOCS_TITLE: 'Dokumentasi',
    DOCS: [
      { label: 'Ringkasan Sistem', href: '/docs' },
      { label: 'Mekanisme Sync Engine', href: '/docs' },
      { label: 'Keamanan Multi-Tenant', href: '/docs' },
      { label: 'Integrasi Webhook', href: '/docs' },
    ],
    COL_CONTACT_TITLE: 'Dukungan & Kontak',
    CONTACT_EMAIL: 'rhankbrguwdev@gmail.com',
    CONTACT_SLA: 'Dukungan Teknis < 24 Jam',
    LOCATION: 'Indonesia • Cloud Architecture',
  },
} as const;

