export const TOAST_IDS = {
  AUTH_ERROR: 'auth-error',
  REQUEST_ERROR: 'request-error',
  IMAGE_ERROR: 'image-error',
  SAVE_SUCCESS: 'save-success',
  SAVE_ERROR: 'save-error',
  ACTION: 'action',
  ACCESS_SUCCESS: 'access-success',
  ACCESS_ERROR: 'access-error',
  ACCESS_REJECTED: 'access-rejected',
  ACCESS_REJECTED_ERROR: 'access-rejected-error',
  ROLE_ERROR: 'role-error',
  REVOKE_ERROR: 'revoke-error',
  INVITE_ERROR: 'invite-error',
  FORM_ERROR: 'form-error',
  SYNC_SUCCESS: 'sync-success',
  SYNC_ERROR: 'sync-error',
  NETWORK_STATUS: 'network-status',
  CHECKOUT_ERROR: 'checkout-error',
} as const;
